server:
    port: 8880
#spring:
#  profiles:
#    active: test
#---
#server:
#    port: 8881
#spring:
#    profiles: dev
#---
#server:
#    port: 8882
#spring:
#    profiles: test


student:
    name: ${student.name}
    age: ${random.int(18,30)}
    adult: true
    hobbies: [basketball,swimming]
    address: {province: 江苏, city: 常州, area: 钟楼区}
    skills: [programming,fitness]
    email: jxu0102@163.com
    pet: {name: 局长, type: hsq}
